### ISSUE TITLE
Page result en anglais

### ISSUE THREAD

**Issue by tokiwi-support** [tokiwi/fairelection#14]
Unnecessary “Help” text in the right hand side of the final results page after the heading “Results” (screenshot in the google doc here, p. 4, Léonard mentined in comment)

https://docs.google.com/document/d/1pll7NUK1zMiVA0gv_yFz7IuhFP1pr-KeyzGyodFbAko/edit#

**Comment by DurandA** [comment]
Fixed, thanks!
