### ISSUE TITLE
Liens page anglais FAQ

### ISSUE THREAD

**Issue by tokiwi-support** [tokiwi/fairelection#15]
Salut l'équipe,
- merci d'avoir ajouté les liens vers les bios des deux chercheurs - possibilité de rester sur le site fairelection en ouvrant un nouveau tab ? 
- il manque toujours le lien vers le papier, sur la même page FAQ (au fond du paragraphe) 
Tout est ici: https://docs.google.com/document/d/1pll7NUK1zMiVA0gv_yFz7IuhFP1pr-KeyzGyodFbAko/edit

**Comment by DurandA** [comment]
Bonjour et merci pour le ticket.

> merci d'avoir ajouté les liens vers les bios des deux chercheurs - possibilité de rester sur le site fairelection en ouvrant un nouveau tab ?

Oui, c'est fait.

> il manque toujours le lien vers le papier, sur la même page FAQ (au fond du paragraphe)

Corrigé.
